dim=(
    10000
    100000
    1000000
    10000000
    #100000000
    #1000000000
    #10000000000
)

var_pairs=(
"QUANT_ALGO=UNIFORM SEND_ALGO=REC_HALVING BITS_VAR=8"
"QUANT_ALGO=UNIFORM SEND_ALGO=REC_HALVING BITS_VAR=16"
"QUANT_ALGO=UNIFORM SEND_ALGO=RING BITS_VAR=8"
"QUANT_ALGO=UNIFORM SEND_ALGO=RING BITS_VAR=16"
"QUANT_ALGO=HOMOMORPHIC SEND_ALGO=REC_HALVING BITS_VAR=8"
"QUANT_ALGO=HOMOMORPHIC SEND_ALGO=REC_HALVING BITS_VAR=16"
"QUANT_ALGO=HOMOMORPHIC SEND_ALGO=RING BITS_VAR=8"
"QUANT_ALGO=HOMOMORPHIC SEND_ALGO=RING BITS_VAR=16"
"QUANT_ALGO=KNOWN_RANGE SEND_ALGO=REC_HALVING BITS_VAR=8"
"QUANT_ALGO=KNOWN_RANGE SEND_ALGO=REC_HALVING BITS_VAR=16"
"QUANT_ALGO=KNOWN_RANGE SEND_ALGO=RING BITS_VAR=8"
"QUANT_ALGO=KNOWN_RANGE SEND_ALGO=RING BITS_VAR=16"
"QUANT_ALGO=LLOYD SEND_ALGO=REC_HALVING BITS_VAR=8"
"QUANT_ALGO=LLOYD SEND_ALGO=REC_HALVING BITS_VAR=16"
"QUANT_ALGO=NON_LINEAR SEND_ALGO=REC_HALVING BITS_VAR=8 NON_LINEAR_TYPE=1"
"QUANT_ALGO=NON_LINEAR SEND_ALGO=REC_HALVING BITS_VAR=8 NON_LINEAR_TYPE=2"
"QUANT_ALGO=NON_LINEAR SEND_ALGO=REC_HALVING BITS_VAR=16 NON_LINEAR_TYPE=1"
"QUANT_ALGO=NON_LINEAR SEND_ALGO=REC_HALVING BITS_VAR=16 NON_LINEAR_TYPE=2"
)

for env_vars in "${var_pairs[@]}"; do
    IFS=' ' read -ra env_array <<< "$env_vars"

    export "${env_array[@]}"
    echo "${env_array[@]}"

    for arg in "${dim[@]}"; do
        echo "Running with dimension: $arg"
        echo "Environmental variables set to $env_vars"

        mpiexec -n 4 ./out "$arg"
    done
done

